FROM debian:trixie

################ METADATA #################
LABEL org.opencontainers.image.authors="Cristian Alonso Contreras (CrIsTiiAnPvP)"
LABEL version="1.0"
LABEL description="Docker image for a BIND9 Dns server."
LABEL website="cristianac.es"
LABEL org.opencontainers.image.source="https://github.com/CrIsTiAnPvP/Mail-Server"
###########################################